config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :locations, only: [:show]
    resources :patients
    root 'patients#index'
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :patients

  validates :name, presence: true, length: { maximum: 80, too_long: "%{count} characters is the maximum allowed" }
  validates :code, length: { maximum: 10, too_long: "%{count} characters is the maximum allowed" }
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :location

  validates :first_name, presence: true, length: {maximum: 30, too_long: "%{count} characters is the maximum allowed"}
  validates :middle_name, length: {maximum: 10, too_long: "%{count} characters is the maximum allowed"}
  validates :last_name, presence: true, length: {maximum: 30, too_long: "%{count} characters is the maximum allowed"}
  validates :gender, inclusion: {in: ["Not available", "Male", "Female"], message: "%{value} is not a valid gender"}
  validates :status, presence: true, inclusion: {in: %w(Initial Referred Treatment Closed), message: "%{value} is not a valid status"}
  validates :location_id, presence: true

  scope :onTreatment, -> {where(status: STATUS_TREATMENT)}
  scope :not_deleted, -> {where(deleted: false)}

  STATUS_INITIAL   = 'Initial'
  STATUS_REFERRED  = 'Referred'
  STATUS_TREATMENT = 'Treatment'
  STATUS_CLOSED    = 'Closed'
  ALL_STATUSES       = [
    STATUS_INITIAL,
    STATUS_REFERRED,
    STATUS_TREATMENT,
    STATUS_CLOSED
  ]

  GENDER_NA        = 'Not available'
  GENDER_MALE      = 'Male'
  GENDER_FEMALE    = 'Female'
  ALL_GENDERS      = [
    GENDER_NA,
    GENDER_MALE,
    GENDER_FEMALE
  ]

  def full_name
    "#{last_name}, #{first_name} #{middle_name}"
  end

  def age
    (Date.today.to_s(:number).to_i - date_of_birth.to_s(:number).to_i)/1e4.to_i
  end

  def medical_record_number
    "MR#{'%06d' % id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_i18n_locale_from_params

  protected
  def set_i18n_locale_from_params
    if params[:locale]
      if I18n.available_locales.map(&:to_s).include?(params[:locale])
        I18n.locale = params[:locale]
      else
        flash.now[:notice] = "#{params[:locale]} translation not available"
        logger.error flash.now[:notice]
      end
    end
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location

  private
  def set_location
    @location = Location.find(params[:id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :is_patient_deleted, only: [:show, :edit, :update, :destroy]
  before_action :increment_view_count, only: [:show]

  # GET /patients
  # GET /patients.json
  def index
    if params[:set_locale]
      redirect_to patients_url(locale: params[:set_locale])
    else
      @patients = Patient.not_deleted
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: I18n.t('patient_creation_succeed') }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: I18n.t('patient_update_succeed') }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.update_attributes(deleted: true)
    respond_to do |format|
      format.html { redirect_to patients_url, notice: I18n.t('patient_marked_delete') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def is_patient_deleted
      if @patient.deleted?
        redirect_to patients_url and return false
      end
    end

    def increment_view_count
      Patient.increment_counter(:view_count, @patient)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :date_of_birth, :gender, :status, :location_id, :view_count, :deleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def choices_for_gender
    Patient::ALL_GENDERS.map {|g| [t("patient.gender.#{g}"), g]}
  end

  def choices_for_status
    Patient::ALL_STATUSES.map {|s| [t("patient.status.#{s}"), s]}
  end

  def choices_for_location
    Location.all.map {|l| [l.name, l.id]}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='banner'>
  <%= form_tag patients_path, class: 'locale', method: 'get' do %>
    <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/locations/show.html.erb
<p>
  <strong><%= t('.name') %>:</strong>
  <%= @location.name %>
</p>

<p>
  <strong><%= t('.code') %>:</strong>
  <%= @location.code %>
</p>

<p>
  <strong><%= t('.patient_list') %>:</strong>
  <ol>
    <% @location.patients.each do |patient| %>
      <li><%= link_to patient.full_name, patient_path(patient) %></li>
    <% end %>
  </ol>
</p>

<%= link_to t('.back'), root_path %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('.error') %></h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, t('.first_name') %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name, t('.middle_name') %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, t('.last_name') %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth, t('.birthday') %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :gender, t('.gender') %><br>
    <%= f.select :gender, choices_for_gender %>
  </div>
  <div class="field">
    <%= f.label :status, t('.status') %><br>
    <%= f.select :status, choices_for_status %>
  </div>
  <div class="field">
    <%= f.label :location_id, t('.location') %><br>
    <%= f.select :location_id, choices_for_location %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit') %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1><%= t('.edit_title') %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @patient %> |
<%= link_to t('.back'), patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title_html') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.mr_html') %></th>
      <th><%= t('.name_html') %></th>
      <th><%= t('.age_html') %></th>
      <th><%= t('.gender_html') %></th>
      <th><%= t('.status_html') %></th>
      <th><%= t('.location_html') %></th>
      <th><%= t('.view_count_html') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.medical_record_number %></td>
        <td><%= patient.full_name %></td>
        <td><%= patient.age %></td>
        <td><%= t("patient.gender.#{patient.gender}") %></td>
        <td><%= t("patient.status.#{patient.status}") %></td>
        <td><%= link_to patient.location.name, location_path(patient.location) %></td>
        <td><%= patient.view_count %></td>
        <td><%= link_to t('.show'), patient %></td>
        <td><%= link_to t('.edit'), edit_patient_path(patient) %></td>
        <td><%= link_to t('.destroy'), patient, method: :delete, data: { confirm: t('.destroy_confirmation') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_patient_path %>

app/views/patients/new.html.erb
<h1><%= t('.new_title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.mr') %>:</strong>
  <%= @patient.medical_record_number %>
</p>

<p>
  <strong><%= t('.name') %>:</strong>
  <%= @patient.full_name %>
</p>

<p>
  <strong><%= t('.birthday') %>:</strong>
  <%= @patient.date_of_birth %>
</p>

<p>
  <strong><%= t('.gender') %>:</strong>
  <%= t("patient.gender.#{@patient.gender}") %>
</p>

<p>
  <strong><%= t('.status') %>:</strong>
  <%= t("patient.status.#{@patient.status}") %>
</p>

<p>
  <strong><%= t('.location') %>:</strong>
  <%= @patient.location.name %>
</p>

<p>
  <strong><%= t('.view_count') %>:</strong>
  <%= @patient.view_count %>
</p>

<%= link_to t('.edit'), edit_patient_path(@patient) %> |
<%= link_to t('.back'), patients_path %>